/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DeviceEditor: typeof import('./src/components/device/device-editor/device-editor.vue')['default']
    DeviceItem: typeof import('./src/components/device/device-item/device-item.vue')['default']
    DeviceList: typeof import('./src/components/device/divice-list/device-list.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    VButton: typeof import('./src/components/ui/v-button/v-button.vue')['default']
  }
}
